Repository k8ssandra/reaper-operator, pull requests merged in 2020-12, with the labels that each got.

#17 K8C-68 Allow autoscheduling to be enabled
  api/v1alpha1/reaper_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/reaper.cassandra-reaper.io_reapers.yaml
  controllers/reaper_controller_test.go
  pkg/reconcile/reconcilers.go
  pkg/reconcile/reconcilers_test.go
Labels: complexity: low

#19 Create bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: complexity: low

#20 create feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: complexity: low

#22 Add ability to use custom images in e2e tests
  .gitignore
  Makefile
  scripts/create-test-overlays.sh
  test/config/deploy_reaper_test/base/kustomization.yaml
  test/config/deploy_reaper_test/base/reaper-operator-patch.yaml
  test/config/deploy_reaper_test/kustomization.yaml
  test/config/deploy_reaper_test/overlays/k8ssandra/kustomization.yaml
  test/framework/framework.go
Labels: complexity: high

#24 Upgrade to Go 1.15
  .github/workflows/build.yml
  Dockerfile
  go.mod
  go.sum
  pkg/reconcile/reconcilers_test.go
  scripts/create-test-overlays.sh
Labels: complexity: low, tech-debt
