Repository k8ssandra/reaper-operator, pull requests merged in 2021-01, with the labels that each got.

#27 upgrade default version to 2.1.3
  api/v1alpha1/reaper_types.go
Labels: complexity: low, enhancement

#21 create support issue template
  .github/ISSUE_TEMPLATE/support.md
Labels: complexity: low, priority: p1

#29 Add support for Cassandra backend authentication using Secrets
  api/v1alpha1/reaper_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/reaper.cassandra-reaper.io_reapers.yaml
  controllers/reaper_controller_test.go
  pkg/config/validate.go
  pkg/config/validate_test.go
  pkg/reconcile/reconcilers.go
  pkg/reconcile/secrets.go
Labels: complexity: medium, priority: p1

#30 update cass-operator dependency
  go.mod
  go.sum
Labels: complexity: low
